# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-03 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaton', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='hash',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='chat',
            name='password_hash',
            field=models.CharField(editable=False, max_length=1024, null=True),
        ),
    ]
